name: Unleash api-tokens

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/unleash-apitoken.yaml'
      - '.nais/dev/unleash-apitoken-tss.yaml'
  workflow_dispatch:

jobs:
  apply-apitoken-unleash:
    name: Apply ApiToken for Unleash to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Deploy to dev (fss)
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/dev/unleash-apitoken-tss.yaml
